---
# tasks file for drupal-apachesolr
- name: Ensure Drupal apachesolr configuration schema.xml applied.
  get_url: "url=http://cgit.drupalcode.org/apachesolr/plain/solr-conf/{{ drupal_apachesolr_solr_conf }}/schema.xml dest=/var/solr/conf/ force=yes"
  notify: restart solr

- name: Ensure Drupal apachesolr configuration solrconfig.xml applied.
  get_url: "url=http://cgit.drupalcode.org/apachesolr/plain/solr-conf/{{ drupal_apachesolr_solr_conf }}/solrconfig.xml dest=/var/solr/conf/ force=yes"
  notify: restart solr

- name: Ensure Drupal apachesolr configuration protwords.txt applied.
  get_url: "url=http://cgit.drupalcode.org/apachesolr/plain/solr-conf/{{ drupal_apachesolr_solr_conf }}/protwords.txt dest=/var/solr/conf/ force=yes"
  notify: restart solr
