---
# tasks file for drupal-apachesolr

- name: Set solr_conf_directory for apachesolr version 3.x.
  set_fact:
    solr_conf_directory: "{{ solr_home }}/conf/"
  when: "solr_version.split('.')[0] == '3'"

- name: Set solr_conf_directory for apachesolr version 4.x.
  set_fact:
    solr_conf_directory: "{{ solr_home }}/collection1/conf/"
  when: "solr_version.split('.')[0] == '4'"

- name: Set solr_conf_directory for apachesolr version 5.x.
  set_fact:
    solr_conf_directory: "{{ solr_home }}/data/collection1/conf/"
  when: "solr_version.split('.')[0] == '5'"

- name: Ensure Drupal apachesolr configuration applied.
  get_url: "url=http://cgit.drupalcode.org/apachesolr/plain/solr-conf/solr-{{ solr_version.split('.')[0] }}.x/{{ item }} dest={{ solr_conf_directory }} force=yes"
  notify: restart solr
  with_items:
    - elevate.xml
    - mapping-ISOLatin1Accent.txt
    - protwords.txt
    - schema.xml
    - schema_extra_fields.xml
    - schema_extra_types.xml
    - solrconfig.xml
    - solrconfig_extra.xml
    - solrcore.properties
    - stopwords.txt
    - synonyms.txt

- name: Ensure Solr conf files are owned by the solr_user.
  file:
    path: "{{ solr_conf_directory }}"
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    recurse: yes
